Join modifications from branch CEAFor_V3_2_0

diff --git a/adm_local/unix/make_conclude.in b/adm_local/unix/make_conclude.in
--- a/adm_local/unix/make_conclude.in
+++ b/adm_local/unix/make_conclude.in
@@ -37,9 +37,9 @@ LIB_OBJ_F    = $(patsubst %.f,   %.lo, $(filter %.f, $(LIB_SRC)))
 # all libtool obj file in library
 LIB_OBJ = $(LIB_OBJ_CXX) $(LIB_OBJ_CC) $(LIB_OBJ_C) $(LIB_CLIENT_OBJ:%.o=%.lo) $(LIB_SERVER_OBJ:%.o=%.lo) $(LIB_SWIG_OBJ) $(LIB_OBJ_F)
 
-# LIB_BUILD = $(LIB:%.la=$(top_builddir)/lib/salome/%.la)
-LIB_BUILD = $(patsubst %.la, $(top_builddir)/lib/salome/%.la, $(filter %.la, $(LIB)))
-LIB_BUILD_A = $(patsubst %.a, $(top_builddir)/lib/salome/%.a, $(filter %.a, $(LIB)))
+# LIB_BUILD = $(LIB:%.la=$(top_builddir)/lib@LIB_LOCATION_SUFFIX@/salome/%.la)
+LIB_BUILD = $(patsubst %.la, $(top_builddir)/lib@LIB_LOCATION_SUFFIX@/salome/%.la, $(filter %.la, $(LIB)))
+LIB_BUILD_A = $(patsubst %.a, $(top_builddir)/lib@LIB_LOCATION_SUFFIX@/salome/%.a, $(filter %.a, $(LIB)))
 
 ifneq ($(findstring cmodule.la,$(filter %.la, $(LIB))),)
 LIB_SWIG = $(patsubst %cmodule.la,%.so, $(filter %.la, $(LIB)))
@@ -50,7 +50,7 @@ endif
 lib: $(LIB_BUILD) $(LIB_CLIENT_PY)
 # we don't build static library !
 
-$(LIB_BUILD): $(top_builddir)/lib/salome/%.la: %.la
+$(LIB_BUILD): $(top_builddir)/lib@LIB_LOCATION_SUFFIX@/salome/%.la: %.la
 	-$(RM) $@
 	-$(RM) $(patsubst %.la, %.so, $@)
 	-$(RM) $(patsubst %.la, %.a, $@)
@@ -61,10 +61,10 @@ $(LIB_BUILD): $(top_builddir)/lib/salome/%.la: %.la
 	      $(patsubst %.la, %.so, $@).0 || true
 
 	if test "X$(LIB_SWIG)" != X; then \
-	   ln -sf $(patsubst %.la,%.so, $(CURDIR)/.libs/$<) $(top_builddir)/lib/salome/_$(LIB_SWIG) || true;\
+	   ln -sf $(patsubst %.la,%.so, $(CURDIR)/.libs/$<) $(top_builddir)/lib@LIB_LOCATION_SUFFIX@/salome/_$(LIB_SWIG) || true;\
 	fi;
 
-$(LIB_BUILD_A): $(top_builddir)/lib/salome/%.a: %.a
+$(LIB_BUILD_A): $(top_builddir)/lib@LIB_LOCATION_SUFFIX@/salome/%.a: %.a
 	-$(RM) $@
 	ln -sf $(CURDIR)/$< $@ || true
 
@@ -108,7 +108,7 @@ $(DEST_PYSCRIPTS): $(top_builddir)/bin/salome/%: %
 
 # copy pyqt files in $(PYTHON_SHARED_SITE)
 #
-PYTHON_SHARED_SITE=$(top_builddir)/lib/python$(PYTHON_VERSION)/site-packages/salome/shared_modules
+PYTHON_SHARED_SITE=$(top_builddir)/lib@LIB_LOCATION_SUFFIX@/python$(PYTHON_VERSION)/site-packages/salome/shared_modules
 
 $(PYTHON_SHARED_SITE):
 	$(INSTALL) -d  $@
@@ -118,11 +118,65 @@ sharedpyscripts: $(PYTHON_SHARED_SITE) $(DEST_SHAREDPYSCRIPTS)
 $(DEST_SHAREDPYSCRIPTS): $(PYTHON_SHARED_SITE)/%: %
 	cp -f $< $@
 
-check: test
+#check: test !!!!   version before AG changes
 
-tests: test
+#tests: test      !!!!   version before AG changes
 
-test: $(LIB) $(TEST_PROGS:%=$(top_builddir)/bin/salome/%) 
+#test: $(LIB) $(TEST_PROGS:%=$(top_builddir)/bin/salome/%)  !!!!   version before AG changes
+
+check: tests
+
+
+
+
+
+runtest_%:
+	@( LD_LIBRARY_PATH=$(top_builddir)/src/MEDMEM/.libs:$(top_builddir)/src/MEDWrapper/V2_1/Core/.libs:$${LD_LIBRARY_PATH} ; \
+	SALOME_trace=local ; \
+	export SALOME_trace ; \
+	x=$@ ; \
+	x=$${x#runtest_*} ; \
+	echo -n "Passing test : "$$x ; \
+	./$$x > /dev/null ; \
+	if test $$? != "0"; then  \
+	  echo $$'\033'[1\;31m [ FAILED ] $$'\033'[0m ; \
+	  exit 2;                                       \
+	else  \
+	  echo  $$'\033'[1\;32m [ OK ] $$'\033'[0m \ ; \
+	fi; )
+
+runpytest_%:
+	@( LD_LIBRARY_PATH=$(top_builddir)/src/MEDMEM/.libs:$(top_builddir)/src/MEDWrapper/V2_1/Core/.libs:$${LD_LIBRARY_PATH} ; \
+	PYTHONPATH=$(top_builddir)/src/MEDMEM_SWIG:$${PYTHONPATH} ; \
+	SALOME_trace=local ; \
+	export SALOME_trace ; \
+	x=$@ ; \
+	x=$${x#runpytest_*} ; \
+	echo -n "Passing python test : "$$x ; \
+	python $(srcdir)/$$x > /dev/null ; \
+	if test $$? != "0"; then  \
+	  echo $$'\033'[1\;31m [ FAILED ] $$'\033'[0m ; \
+	  exit 2;                                       \
+	else  \
+	  echo  $$'\033'[1\;32m [ OK ] $$'\033'[0m \ ; \
+	fi; )
+
+ALL_CHECK_TARGETS = $(patsubst %, runtest_%, $(TEST_PROGS)) 
+
+tests: $(LIB) $(TEST_PROGS) $(ALL_CHECK_TARGETS)
+	@ln -fs $(top_builddir)/src/MEDMEM_SWIG/.libs/libMEDMEM_Swigcmodule.so $(top_builddir)/src/MEDMEM_SWIG/_libMEDMEM_Swig.so ; \
+	for f in $(TEST_PYSCRIPTS); do            \
+	  if [ x"$${f#*test}" != x"$${f}" ]; then    \
+	     $(MAKE) runpytest_$$f ; \
+	     if test $$? != "0"; then  \
+	        rm -f $(top_builddir)/src/MEDMEM_SWIG/_libMEDMEM_Swig.so ; \
+	        exit 2; \
+	     fi; \
+	  fi;  \
+	done ; \
+	rm -f $(top_builddir)/src/MEDMEM_SWIG/_libMEDMEM_Swig.so ;
+
+
 
 
 # copy header file in $(inc_builddir)
@@ -141,6 +195,7 @@ $(libdir) $(includedir) $(bindir) $(datadir) $(idldir) $(sharedpydir):
 
 # Install the library, the public header files, and programs.
 install: $(LIB) $(BIN) $(TEST_PROGS) $(libdir) $(includedir) $(bindir) $(datadir) $(idldir) install-python install-sharedpyqt install-qm
+#install: $(LIB) $(BIN) $(libdir) $(includedir) $(bindir) $(datadir) $(idldir) install-python install-sharedpyqt install-qm
 	@for f in X $(LIB); do						      \
 	   if test $$f != X; then					      \
 	      ($(LT_INSTALL_LIB) $$f $(libdir)/. || exit 1);		      \
@@ -262,10 +317,10 @@ clean: mostlyclean
 	-$(RM) $(LIB) $(TEST_PROGS) $(BIN) $(CLEAN)
 	-$(RM) TAGS *~ *# core *.core 
 	-$(RM) -r .libs
-	-$(RM) $(top_builddir)/lib/salome/$(LIB)
+	-$(RM) $(top_builddir)/lib@LIB_LOCATION_SUFFIX@/salome/$(LIB)
 	-$(RM) $(patsubst %,$(top_builddir)/bin/salome/%, $(BIN))
-	-$(RM) $(patsubst %.la, %.so, $(top_builddir)/lib/salome/$(LIB))
-	-$(RM) $(patsubst %.la, %.a, $(top_builddir)/lib/salome/$(LIB))
+	-$(RM) $(patsubst %.la, %.so, $(top_builddir)/lib@LIB_LOCATION_SUFFIX@/salome/$(LIB))
+	-$(RM) $(patsubst %.la, %.a, $(top_builddir)/lib@LIB_LOCATION_SUFFIX@/salome/$(LIB))
 # remove idl generated files (sources)
 	-$(RM) $(LIB_CLIENT_SRC) $(LIB_SERVER_SRC) $(BIN_CLIENT_SRC) $(BIN_SERVER_SRC)
 # remove idl generated files (headers)
